// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJBv272sFkPy6qTjVnzYvIDAFHQ-jBAc',
    appId: '1:840212005267:web:ae84682c5bbb20b1c5a866',
    messagingSenderId: '840212005267',
    projectId: 'fir-memo-app-fff8a',
    authDomain: 'fir-memo-app-fff8a.firebaseapp.com',
    storageBucket: 'fir-memo-app-fff8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpkd5sYDiOEHaaoZO0pm4NzIQ1mnPD_90',
    appId: '1:840212005267:android:c2b6d5e381633d21c5a866',
    messagingSenderId: '840212005267',
    projectId: 'fir-memo-app-fff8a',
    storageBucket: 'fir-memo-app-fff8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWZ3G_QX_0r6YwDE3UrJ2At9AexZ99Gjc',
    appId: '1:840212005267:ios:4457e2eb25d914efc5a866',
    messagingSenderId: '840212005267',
    projectId: 'fir-memo-app-fff8a',
    storageBucket: 'fir-memo-app-fff8a.firebasestorage.app',
    iosBundleId: 'com.example.snsApp',
  );
}
